# Generated by Django 3.0.1 on 2020-01-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200113_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userID',
            field=models.CharField(blank=True, help_text='Please enter the 14 digit identification to allow us to connect you to the database', max_length=14),
        ),
    ]
