# Generated by Django 3.0.1 on 2020-01-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200113_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userID',
            new_name='accountID',
        ),
    ]
