# Generated by Django 3.0.1 on 2020-03-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gotAccount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accountID',
            field=models.CharField(blank=True, help_text='Enter Account ID to link us to your debit/credit card', max_length=14),
        ),
    ]
