# Generated by Django 3.0.1 on 2020-03-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200313_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gotAccount',
            field=models.IntegerField(),
        ),
    ]
