# Generated by Django 3.0.1 on 2020-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200313_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transPerPage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gotAccount',
            field=models.CharField(max_length=1),
        ),
    ]
