# Generated by Django 3.0.1 on 2020-03-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200314_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gotAccount',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transPerPage',
            field=models.CharField(default='10', max_length=14),
        ),
    ]
