# Generated by Django 3.0.1 on 2020-03-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200314_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateRange',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='useDateFilter',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
