# Generated by Django 3.0.1 on 2020-01-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
